# Generated by Django 3.1.4 on 2021-04-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='moviestype',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
